# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AFNetWorkingDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AFNetWorkingDemo

#pod 'AFNetworking', '3.2.1'

  target 'AFNetWorkingDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AFNetWorkingDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
